apiVersion: litmuschaos.io/v1alpha1
kind: ChaosEngine
metadata:
  name: k6-loadgen-engine
  namespace: litmus
spec:
  engineState: "active"
  chaosServiceAccount: litmus     # ensure this SA exists
  appinfo:
    appns: litmus
    applabel: "app=front-end"     # match your deployment
    appkind: deployment
  experiments:
    - name: k6-loadgen
      spec:
        components:
          env:
            - name: TOTAL_CHAOS_DURATION
              value: "60"
            - name: RAMP_TIME
              value: "10"
            - name: SCRIPT_SECRET_NAME
              value: "k6-script"
            - name: SCRIPT_SECRET_KEY
              value: "script.js"